/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPayableOwnerInterface extends Interface {
  getFunction(nameOrSignature: "payMe"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ThankYou"): EventFragment;

  encodeFunctionData(functionFragment: "payMe", values?: undefined): string;

  decodeFunctionResult(functionFragment: "payMe", data: BytesLike): Result;
}

export namespace ThankYouEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    message: string
  ];
  export type OutputTuple = [from: string, to: string, message: string];
  export interface OutputObject {
    from: string;
    to: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPayableOwner extends BaseContract {
  connect(runner?: ContractRunner | null): IPayableOwner;
  waitForDeployment(): Promise<this>;

  interface: IPayableOwnerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  payMe: TypedContractMethod<[], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "payMe"
  ): TypedContractMethod<[], [void], "payable">;

  getEvent(
    key: "ThankYou"
  ): TypedContractEvent<
    ThankYouEvent.InputTuple,
    ThankYouEvent.OutputTuple,
    ThankYouEvent.OutputObject
  >;

  filters: {
    "ThankYou(address,address,string)": TypedContractEvent<
      ThankYouEvent.InputTuple,
      ThankYouEvent.OutputTuple,
      ThankYouEvent.OutputObject
    >;
    ThankYou: TypedContractEvent<
      ThankYouEvent.InputTuple,
      ThankYouEvent.OutputTuple,
      ThankYouEvent.OutputObject
    >;
  };
}
