/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControlEnumerable } from "./AccessControlEnumerable";
export type { IAccessControlEnumerable } from "./IAccessControlEnumerable";
