/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { Storage__factory } from "./Storage__factory";
export { StorageUpgr__factory } from "./StorageUpgr__factory";
