/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPayableOwner__factory } from "./IPayableOwner__factory";
export { IStorage__factory } from "./IStorage__factory";
