/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStorage,
  IStorageInterface,
} from "../../../contracts/interfaces/IStorage";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "Stored",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "ThankYou",
    type: "event",
  },
  {
    inputs: [],
    name: "payMe",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStorage__factory {
  static readonly abi = _abi;
  static createInterface(): IStorageInterface {
    return new Interface(_abi) as IStorageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IStorage {
    return new Contract(address, _abi, runner) as unknown as IStorage;
  }
}
