/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { AccessControl } from "./AccessControl";
export type { IAccessControl } from "./IAccessControl";
export type { Ownable } from "./Ownable";
